name: Build and Release .deb Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dpkg dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Build .deb package
        run: dpkg-deb -Z gzip --build src patch.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: patch.deb
          path: patch.deb

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download built package
        uses: actions/download-artifact@v3
        with:
          name: patch.deb

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: patch.deb
          asset_name: patch.deb
          asset_content_type: application/x-debian-package